### ISSUE TITLE
Allow to pass style/className to TransformWrapper & TransformComponent

### ISSUE THREAD

**Issue by caub** [BetterTyped/react-zoom-pan-pinch#521]
**Is your feature request related to a problem? Please describe.**
I'd like to pass either `className="d-flex flex-column flex-1"` or `style={{ display: 'flex', flexDirection: 'column', flex: 1 }}` to both `TransformWrapper` and `TransformComponent`

The goal is to make the component fill all content horizontally

**Describe alternatives you've considered**
For now I'll apply these styles from the parent element, but it's not ideal, it could break if you change your classes

```css
.react-transform-wrapper, .react-transform-component {
  display: flex;
  flex-direction: column;
  flex: 1;
}
```
